config/routes.rb
Alabs::Application.routes.draw do

  get 'about' => 'pages#about'
  get 'services' => 'pages#services'
  get 'customers' => 'pages#customers'
  get 'software' => 'pages#software'
  get 'contact' => 'pages#contact'
  post 'contact' => 'pages#contact_message_received'

  root :to => 'pages#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  
  validates_presence_of :name
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :subject
  validates_presence_of :body

  attr_accessible :name, :email, :subject, :body, :mailing
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  protected

  # Método para decirle a Varnish, u otros caches,
  # qué tiene que cachear
  def set_http_cache(period, visibility = false)
    expires_in period, :public => visibility, 'max-stale' => 0
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  caches_page :about, :services, :customers, :software

  def index
    # Para pillar los titulares del blog
    require 'rss'
    rss_feed = "http://feeds.feedburner.com/alabs/blog"
    rss = RSS::Parser.parse(rss_feed, false)
    @posts = []
    rss.items.each_with_index do |i, n|
      break if n == 5
      item = { 
        'link' => i.link,
        'title' => i.title,
      }
      @posts << item
    end
    @posts

    # Mostrar los últimos tweets
    @tweets = Twitter.user_timeline('alabs_es')[0,4]
    
    set_http_cache(3.hours, visibility = true)
  end

  def about
    set_http_cache(6.hours, visibility = true)
  end

  def services
    set_http_cache(6.hours, visibility = true)
  end

  def customers
    set_http_cache(6.hours, visibility = true)
  end

  def software
    set_http_cache(6.hours, visibility = true)
  end

  def contact
    @contact = Contact.new
  end

  def contact_message_received
    @contact = Contact.new(params[:contact])
    if @contact.save
      Mailman.contact(@contact).deliver
      flash[:notice] = 'Tu mensaje ha sido recibido, pronto nos pondremos en contacto.'
      redirect_to root_url
    else
      flash[:error] = 'Verifica los campos en rojo'
      render :action => :contact
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'active' : ''

    content_tag(:li, :class => class_name) do
      link_to link_text, link_path
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8" />
    <title><%= @page_title %> - aLabs</title>
    <%= stylesheet_link_tag 'application', :media => 'all' %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <link rel="alternate" type="application/rss+xml" title="aLabs &raquo; Feed" href="http://feeds.feedburner.com/alabs/blog" />
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-20296032-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
    <link href="https://plus.google.com/110799938491152815749/" rel="publisher" />
  </head>
  <body class="<%= params[:action] %>_action">
    <div id="header">
      <div class="page">
        <%= link_to 'aLabs', root_path, :class => 'logo', :title => 'Ir al inicio' %>
        <ul>
          <%= nav_link 'Nosotros', about_path %>
          <%= nav_link 'Servicios', services_path %>
          <%= nav_link 'Casos de Éxito', customers_path %>
          <%= nav_link 'Software', software_path %>
          <li><%= link_to 'Residencia', 'http://blog.alabs.es/category/residencia-alabs/' %></li>
          <li><%= link_to 'Blog', 'http://blog.alabs.es/' %></li>
          <%= nav_link 'Contacto', contact_path %>
        </ul>
        <div class="clear"></div>
      </div>
    </div><!-- header -->
    <div id="page">
      <div class="top top_<%= params[:action] %>">&nbsp;</div>
      <div class="content">
        <%= yield %>
      </div><!-- content -->
      <div class="bottom"></div>
    </div><!-- page -->
    <div id="footer" class="page">
      <p>Copyright &copy; 2010 - <%= Time.now.year %> aLabs. Este sitio tiene <%= link_to 'esta licencia', 'http://creativecommons.org/licenses/by-sa/3.0/deed.es_ES' %> Creative Commons.</p>
      <ul>
        <li><%= link_to 'Inicio', root_path %></li>
        <li><%= link_to 'Nosotros', about_path %></li>
        <li><%= link_to 'Servicios', services_path %></li>
        <li><%= link_to 'Blog', '#' %></li>
        <li><%= link_to 'Contacto', contact_path %></li>
        <li style="margin-top: -5px;"><%= link_to image_tag('logo-small.png'), root_path %></li>
      </ul>
      <div class="clear"></div>
    </div>
  </body>
</html>

app/views/mailman/contact.text.erb
<%= @message_body %>

app/views/pages/_right_sidebar.html.erb
<div class="right">
  <div class="sidebar_box">
    <h4>Sidebar Example</h4>
    <p>Aenean diam massa, fringilla quis consectetur et, iaculis id mi. Curabitur turpis risus, pharetra eget pretium id, lobortis sit amet elit. lum convallis pulvinar aliquet. Donec tincidunt adipiscing velit, in commodo leo.</p>
  </div>
  <div class="sidebar_box">
    <h4>An Unordered List</h4>
    <ul>
      <li>A Random Option</li>
      <li>Another Option</li>
      <li>A Third Option</li>
      <li>And a Forth Option</li>
    </ul>
  </div>
  <div class="sidebar_box">
    <h4>Contact Us</h4>
    <p>Still have questions? <a href="#">Contact us</a>.</p>
  </div>
</div><!-- right -->
<div class="clear"></div>

app/views/pages/about.html.erb
<% @page_title = 'Nosotros' %>

<div class="header page">
  <h1>Nosotros</h1>
</div>
<div class="padding">
  <div class="left" class="about">
    <h4>¿Qué es aLabs y qué hacemos?</h4>
    <br />
    <p style="text-align:justify;"><em>"Las «empresas» con orientación política no son solo planes B: producen, conservan y difunden el conocimiento técnico; disponen y proveen de recursos físicos y simbólicos; permiten abolir la división entre trabajo y militancia; atesoran conocimiento organizativo y operacional. Son la evolución natural para un hacking activista que se hace mayor. Un magnífico plan A."</em> (<a href="http://www.espaienblanc.net/IMG/pdf/3_politizacionesenelciberespacio.pdf">Marga Padilla</a>)</p>
    <p style="text-align:justify;">Como asociación sin ánimo de lucro, en aLabs ayudamos a proyectos de software libre a desarrollarse, a asociaciones e instituciones a usar las nuevas tecnologías y a todo tipo de organizaciones a superar las barreras tecnológicas y avanzar en la mejora de sus sistemas. Creemos que una sociedad libre, conectada y activa, es la mejor garantía para un avanzar hacia un nuevo modelo necesario.</p>
  <p style="text-align:justify;">La asociación aLabs da prioridad a los laboratorios de experimentación y transformación de la cultura hacker, para ayudar a desarrollar proyectos que desde la autogestión sin organización son muy complejos, para liberar código que innove y permita usar plataformas libres, gestionadas en canales sin ánimo de lucro y conectadas a los movimientos sociales y culturales locales.</p>
  <p style="text-align:justify;">De ahí nacen herramientas como oiga.me, nolotiro.org, liberateca o PrecaJobs. Plataformas realizadas y liberadas con software libre, que dan servicio cotidiano a decenas de miles de personas; facilitando la creación de campañas de movilización ciudadana, la posibilidad de compartir enlaces y defender tus derechos en la red, reciclar y permitir que las personas compartan objetos que pensaban tirar a la basura de manera masiva o visibilizar  la precarización laboral de nuestras vidas. Ejemplos prácticos que permiten a la sociedad civil organizarse en multitud sin depender de inversores, accionistas o especuladores culturales.</p>
  <p style="text-align:justify;">Las acciones de esta asociación recogen el sentido práctico de las formas de organización hacker mediante nuevas tecnologías, jugando con la estética de la red y facilitando la conexión entre hackers, creadores y espacios contraculturales en el centro de Madrid, investigando el embrión de un nuevo modelo de residencias P2P donde la conectividad a la realidad local de los residentes sea una de las prioridades. Un espacio de trabajo colaborativo y circulación de saberes para artistas y creadores relacionados con arte y software radical, multimedia, comunicación, sociedad red y nuevas tecnologías, formado por diversos espacios-residencia en red que compartan recursos para este proyecto.</p>
  </div><!-- left -->
  <%= render :partial => 'partials/about_sidebar' %>
</div>

app/views/pages/contact.html.erb
<% @page_title = 'Contacto' %>

<div class="header page">
  <h1>Contacto</h1>
</div>
<div class="padding">
  <div class="left">
    <h4>Ponte en contacto con nosotros</h4>
    <br />
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mi mauris, ultricies id dictum a, malesuada sit amet diam. Nullam facilisis, sem sit amet ornare dapibus, lorem orci mattis orci, a pharetra tellus diam sed enim. Nulla viverra ultrices convallis. Etiam eleifend molestie rhoncus.</p>
    <div id="contact-form">
      <%= form_for @contact, :url => contact_path do |f| %>
        <div id="contact-form-fields">
          <div class="contact-field">
            <%= f.label :nombre %>
            <%= f.text_field :name, :placeholder => 'Tu nombre' %>
            <% if @contact.errors[:name] %>
              <span class="error_message"><%= @contact.errors[:name].to_sentence %></span>
            <% end %>
          </div>
          <div class="contact-field">
            <%= f.label :correo_electrónico %>
            <%= f.text_field :email, :placeholder => 'you@example.com' %>
            <% if @contact.errors[:email] %>
              <span class="error_message"><%= @contact.errors[:email].to_sentence %></span>
            <% end %>
          </div>
          <div class="contact-field">
            <%= f.label :asunto %>
            <%= f.text_field :subject, :placeholder => 'Asunto descriptivo' %>
            <% if @contact.errors[:subject] %>
              <span class="error_message"><%= @contact.errors[:subject].to_sentence %></span>
            <% end %>
          </div>
          <div class="contact-field">
            <%= f.label :mensaje %>
            <%= f.text_area :body, :cols => 50, :rows => 10, :placeholder => 'Cuéntanos, estaremos encantados de atenderte.' %>
            <% if @contact.errors[:body] %>
              <span class="error_message"><%= @contact.errors[:body].to_sentence %></span>
            <% end %>
          </div>
          <div class="contact-field">
            <%= f.check_box :mailing %> Deseo subscribirme a la lista de correo de aLabs
          </div>
          <div class="contact-actions">
            <%= f.submit 'Enviar Mensaje' %>
          </div>
        </div><!-- contact-form-fields -->
      <% end %>
    </div><!-- contact-form -->
    <div class="clear"></div>
  </div><!-- left -->
  <%= render :partial => 'partials/contact_sidebar' %>
</div>

app/views/pages/customers.html.erb
<% @page_title = 'Clientes' %>

<div class="header page">
  <h1>Casos de Éxito</h1>
</div>
<div class="padding" style="background-color:#fff;">
  <div class="left">
    <h4>¿Qué hemos hecho y para quién?</h4>
    <br />
    <h5>OASIS</h5>
    <p>Desde el consorcio Oasis nos llegó como encargo realizar una maqueta de gestión de tramos de autopistas del futuro, un desarrollo web con Ruby on Rails y JavaScript, la marca de la casa. Entregamos el proyecto a principios de febrero para su presentación pública en las oficinas de OHL.</p>

    <p>“El proyecto Operación de Autopistas Seguras, Inteligentes y Sostenibles (OASIS), primer proyecto español en abordar el diseño de la autopista del futuro, se enmarca dentro del programa CENIT, cuyo objetivo principal es la financiación de grandes proyectos integrados de colaboración público-privada en investigación industrial de carácter estratégico.</p>

    <p>Esta iniciativa se ha puesto en marcha dirigida por OHL Concesiones e Iridium, con la colaboración principal del Grupo de Gestión de Infraestructuras Abertis, Indra y Sice, y con la participación de un total de 16 empresas españolas, entre las que destacan Geocisa, GMV y los grupos constructores Dragados y OHL. Además, el proyecto cuenta con la inestimable presencia de 7 PYMEs que participan en líneas concretas de investigación.</p>

    <p>Este consorcio de empresas ha seleccionado, para liderar científicamente el proyecto, a 16 de los más importantes grupos de investigación pertenecientes a diversas universidades y centros tecnológicos distribuidos por todo el territorio nacional. Para el desarrollo del proyecto se han definido 7 paquetes de trabajo, cada uno de ellos liderado por una de las principales empresas asociadas, abarcando diferentes campos de investigación entre los que destacan los procesos constructivos, los nuevos sistemas inteligentes de transporte (ITS) en el ámbito de la seguridad y la movilidad, la interacción con el medio ambiente y la optimización energética.“</p>

    <h5>Consultoría Foofind</h5>
    <p>Estudiar cómo mejorar el rendimiento de los servidores de un buscador del tamaño de foofind.com ha sido uno de nuestros proyectos más interesantes. Entre las tareas más delicadas nos encontramos optimizando más de 480 GigaBytes en base de datos repartidas entre distintas instancias MongoDB, usando Sphinx como buscador y estudiando el despliegue de Puppet(enlace) para integración de sistemas y Zabbix(enlace) para monitorización.</p>

    <h5>Taller en Master EOI:  Comunicación organizacional a través de telefonía IP.</h5>
    <p>La EOI (Escuela de Organización Industrial) ha contactó con Login_Madrid (http://www.eoi.es/blogs/login_madrid/2011/03/17/una-centralita-de-telefonos-para-el-trabajo-en-equipo/) y aLabs para impartir un taller simultáneo sobre nuevos usos de la telefonía IP en el ámbito empresarial a sus alumnos de postgrado.</p>

    <p>El taller se realizó simultáneamente (http://www.eoi.es/blogs/login_madrid/2011/04/11/comunicacion-organizacional-a-traves-de-la-voz-ip/)  en las sedes de la EOI en Madrid y Sevilla. La tecnología que usamos en este taller fué una centralita telefónica en la nube, gestionada con Asterisk, un proxy SIP con Kamailio y pasarela SMS para integrarlo todo en un Samsung Galaxy Tab con Android. Aún así, la tecnología es solo una parte, la comunicación organizacional requiere canales y tecnologías, pero los canales y las tecnologías, por si solos, no garantizan la comunicación.</p>

    <h5>Plataforma oiga.me</h5>
    <p>oiga.me es una plataforma de acción y movilización ciudadana, una herramienta de democracia participativa a través de sistemas web y correo electrónico para colectivos, entidades o asociaciones que desean ser escuchados. Ruby on Rails, JavaScript y HTML5 son el corazón de esta plataforma libre que multiplica la potencia de miles de pequeños esfuerzos individuales en una poderosa fuerza colectiva.</p>

    <h5>Telefonía IP segura</h5>
    <p>Nuestro sistema de telefonía segura, con cifrado SRTP, Kamailio y Asterisk. Tras testearlo por tres meses en producción con la telefonía de la asociación estamos montando una plataforma de comunicación segura con SRTP, SIPS(enlaces a todo), Android y conexión a telefonía RTB y celular para ofrecerla como servicio. De esta forma, podremos ofrecer numeración geográfica (DID) para que puedas atender de manera segura las llamadas de tu organización en tu dispositivo móvil preferido allá donde te encuentres, con extensiones internas para el resto de miembros de tu organización y la tranquilidad de usar tecnologías libres y estándares que permitirán nuevos servicios.</p>
  </div><!-- left -->
  <%= render :partial => 'partials/customers_sidebar' %>
</div>

app/views/pages/index.html.erb
<% @page_title = 'Inicio' %>

<div class="header header_home page" style="padding-bottom:10px;">
  <div class="prige_tag"></div>
  <%= image_tag('screenshot.jpg', :class => 'main_screenshot') %>
  <div class="info">
    <h1>oiga.me, tu plataforma de movilización ciudadana</h1>
    <p style="text-align:justify;">oiga.me es una plataforma de acción y movilización ciudadana, una herramienta de participación democrática. A través de oiga.me podrás lanzar peticiones que sean firmadas por miles de personas, por ejemplo, contra los recortes en educación y sanidad pero, además, con un click, tú y todos los que participen podréis mandar mails directamente a los responsables de dichas políticas.</p>
    <a href="http://oiga.me/" class="button icon"><%= image_tag('go_icon.png') %><span>Visita oiga.me</span></a>
    <span class="trial">Puede ser beneficioso para la democrácia de su estado.</span>
  </div>
  <div class="clear"></div>
</div><!-- header_home -->
<div id="home" class="padding">
  <div id="services">
    <div class="section_title">
      <h3>Servicios</h3>
    </div>
    <p style="text-align:justify;">
      <b>Hosting</b>
      <%= image_tag('archive.png') %>
      ¿En que tipo de entidad inviertes el dinero de tu hosting? Una forma de apoyar oiga.me, nolotiro.org y demás proyectos de aLabs es usando nuestro hosting, invierte tu dinero de forma responsable, solo usamos software libre.
    </p>
    <p style="text-align:justify;">
      <b>Telefonía</b>
      <%= image_tag('comment.png') %>
      Tu propia centralita en Internet, con numeración geográfica y extensiones, menús para organizar tus llamadas y estar localizable en cualquier pare del mundo, todo con SRTP (cifrado) para tu privacidad.
    </p>
    <p class="last" style="text-align:justify;">
      <b>Residencia aLabs</b>
      <%= image_tag('contact.png') %>
      Laboratorio y espacio de residencia para creadores hacker dispuestos a liarla, porque de la unión de arte, la tecnología y política nace el desarrollo del futuro.
    </p>
	  <div class="clear spacer"></div>
    <p style="text-align:justify;">
      <b>Desarrollo</b>
      <%= image_tag('file.png') %>
      Aplicaciones web usando como framework Ruby on Rails + HTML5, CSS3 y JavaScript. Si tienes alguna idea en la que necesitas ayuda, no dudes en ponerte en contacto con nosotros.
    </p>
    <p style="text-align:justify;">
      <b>Aplicaciones para móviles</b>
      <%= image_tag('shopping_cart.png') %>
      Aplicaciones pensadas para dispositivos móviles, ya sea mediante servicio web multiplataforma o desarrollo de aplicaciones Android, el presente es móvil y aLabs sabe construirlo e integrarlo.
    </p>
    <p class="last" style="text-align:justify;">
      <b>Eventos / Formación</b>
      <%= image_tag('calendar.png') %>
      Acompañamos a tu organización, si necesitas formación en estándares o tecnologías libres, o realizar un evento tecnológico, puedes contactar con el equipo de asesoría de aLabs.
    </p>
    <div class="clear"></div>
  </div><!-- features -->
  <div id="features">
    <div class="section_title">
      <h3>Últimas noticias</h3>
    </div>
    <div id="blog-news">
      <b>Blog de aLabs</b>
      <ul>
        <% @posts.each do |post| %>
          <li style="margin-bottom: 8px;"><%= link_to post['title'], post['link'] %></li>
        <% end %>
      </ul>
    </div>
    <div id="alabs-social">
      <b>aLabs Social</b>
      <ul>
        <% @tweets.each do |tweet| %>
          <li style="margin-bottom: 8px;"><%= tweet.text %></li>
        <% end %>
      </ul>
    </div>
    <div id="contact">
      <b>Contáctanos</b>
      <p>Puedes llamarnos de forma gratuita usando tu navegador y pulsando el siguiente botón.</p>
      <input id="call" type="button" disabled="true" value="Cargando..." />
      <span id="status"></span>
    </div> 
	  <div class="clear spacer"></div>
  </div><!-- screenshots -->
</div><!-- padding -->

app/views/partials/_about_sidebar.html.erb
<div class="right">
  <div class="sidebar_box">
    <h4>Nosotros</h4>
    <p>La asociación aLabs da prioridad a los laboratorios de experimentación y transformación de la cultura hacker, para ayudar a desarrollar proyectos profesionales desde la autogestión.</p>
  </div>
  <div class="sidebar_box">
    <h4>Algunos de nuestros proyectos</h4>
    <ul>
      <li><%= link_to 'oiga.me', 'http://oiga.me/' %></li>
      <li><%= link_to 'nolotiro.org', 'http://nolotiro.org/' %></li>
      <li><%= link_to 'Liberateca', 'http://liberateca.net/' %></li>
      <li><%= link_to 'Precajobs', 'http://precajobs.net/' %></li>
    </ul>
  </div>
  <div class="sidebar_box">
    <h4>Contáctanos</h4>
    <p>¿Todavía tienes dudas? Puedes <%= link_to 'contáctarnos', contact_path %>.</p>
  </div>
</div><!-- right -->
<div class="clear"></div>

app/views/partials/_contact_sidebar.html.erb
<div class="right">
  <div class="sidebar_box">
    <h4>Contacto</h4>
    <p>Estaremos encontados de atenderte. Puedes escribirnos a hola [at] alabs.es o llamarnos al:<br/> (+34) 91 771 40 52</p>
  </div>
  <div class="sidebar_box">
    <h4>Algunos de nuestros proyectos</h4>
    <ul>
      <li><%= link_to 'oiga.me', 'http://oiga.me/' %></li>
      <li><%= link_to 'nolotiro.org', 'http://nolotiro.org/' %></li>
      <li><%= link_to 'Liberateca', 'http://liberateca.net/' %></li>
      <li><%= link_to 'Precajobs', 'http://precajobs.net/' %></li>
    </ul>
  </div>
  <div class="sidebar_box">
    <h4>Contáctanos</h4>
    <p>¿Todavía tienes dudas? Puedes <%= link_to 'contáctarnos', contact_path %>.</p>
  </div>
</div><!-- right -->
<div class="clear"></div>

app/views/partials/_customers_sidebar.html.erb
<div class="right">
  <div class="sidebar_box">
    <h4>Casos de Éxito</h4>
    <p>Nolotiro.org sirve más de 1.100.000 páginas mensuales y facilita que más de 4.000 objetos se intercambien cada més en vez de ir a la basura, oiga.me da voz a movilizaciones ciudadanas protegiendo los datos de los participantes, liberateca comparte miles de enlaces a contenidos.</p>
  </div>
  <div class="sidebar_box">
    <h4>Algunos de nuestros proyectos</h4>
    <ul>
      <li><%= link_to 'oiga.me', 'http://oiga.me/' %></li>
      <li><%= link_to 'nolotiro.org', 'http://nolotiro.org/' %></li>
      <li><%= link_to 'Liberateca', 'http://liberateca.net/' %></li>
      <li><%= link_to 'Precajobs', 'http://precajobs.net/' %></li>
    </ul>
  </div>
  <div class="sidebar_box">
    <h4>Contáctanos</h4>
    <p>¿Todavía tienes dudas? Puedes <%= link_to 'contáctarnos', contact_path %>.</p>
  </div>
</div><!-- right -->
<div class="clear"></div>

app/views/partials/_services_sidebar.html.erb
<div class="right">
  <div class="sidebar_box">
    <h4>Servicios</h4>
    <p>¿En que tipo de entidad inviertes el dinero? Una forma de apoyar oiga.me, nolotiro.org y demás proyectos de aLabs es usando nuestro nuestros servicios, invierte tu dinero de forma responsable, solo usamos software libre.</p>
  </div>
  <div class="sidebar_box">
    <h4>Algunos de nuestros proyectos</h4>
    <ul>
      <li><%= link_to 'oiga.me', 'http://oiga.me/' %></li>
      <li><%= link_to 'nolotiro.org', 'http://nolotiro.org/' %></li>
      <li><%= link_to 'Liberateca', 'http://liberateca.net/' %></li>
      <li><%= link_to 'Precajobs', 'http://precajobs.net/' %></li>
    </ul>
  </div>
  <div class="sidebar_box">
    <h4>Contáctanos</h4>
    <p>¿Todavía tienes dudas? Puedes <%= link_to 'contáctarnos', contact_path %>.</p>
  </div>
</div><!-- right -->
<div class="clear"></div>

app/views/partials/_software_sidebar.html.erb
<div class="right">
  <div class="sidebar_box">
    <h4>Software</h4>
    <p>Aplicaciones libres para una sociedad libre. Con estas herramientas aLabs facilita que decenas de miles de personas puedan organizar movilizaciones, reciclar y compartir. denunciar explotación laboral o compartir enlaces de manera masiva.</p>
  </div>
  <div class="sidebar_box">
    <h4>Algunos de nuestros proyectos</h4>
    <ul>
      <li><%= link_to 'oiga.me', 'http://oiga.me/' %></li>
      <li><%= link_to 'nolotiro.org', 'http://nolotiro.org/' %></li>
      <li><%= link_to 'Liberateca', 'http://liberateca.net/' %></li>
      <li><%= link_to 'Precajobs', 'http://precajobs.net/' %></li>
    </ul>
  </div>
  <div class="sidebar_box">
    <h4>Contáctanos</h4>
    <p>¿Todavía tienes dudas? Puedes <%= link_to 'contáctarnos', contact_path %>.</p>
  </div>
</div><!-- right -->
<div class="clear"></div>